sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    bucket-name: web-tlias-demo9527
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxec27142052b1295d
    secret: 22987916d5089d3dc62287fc66d44e6a